{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"거래처\",\"날짜\",\"판매\",\"제품\",\"_측정값\",\"대여소현황\",\"자전거_대여이력\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      }
    ],
    "culture": "ko-KR",
    "cultures": [
      {
        "name": "ko-KR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "dim_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "DimDate": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "dim moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "dim_date.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "dim_date.date.변형.날짜_계층": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "Hierarchy": "날짜 계층",
                    "VariationSet": "변형",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "날짜 계층": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "dim_date.date.변형.날짜_계층.분기": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "분기",
                    "VariationSet": "변형",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "분기": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date 분기": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment 분기": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period 분기": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "dim_date.date.변형.날짜_계층.연도": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "연도",
                    "VariationSet": "변형",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "연도": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date 연도": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment 연도": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period 연도": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "dim_date.date.변형.날짜_계층.월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "월",
                    "VariationSet": "변형",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "월": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date 월": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment 월": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period 월": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "dim_date.date.변형.날짜_계층.일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "일",
                    "VariationSet": "변형",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "일": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date 일": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment 일": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period 일": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "dim_date.연도": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "연도"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "연도": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "dim_date.월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "월"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "월": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_측정값_측정값": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_측정값"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_측정값": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_측정값_측정값.열1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_측정값",
                    "ConceptualProperty": "열1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "열1": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "거래처": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "거래처"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "거래처": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "거래처.거래처명": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "거래처",
                    "ConceptualProperty": "거래처명"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "거래처명": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "거래처.거래처코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "거래처",
                    "ConceptualProperty": "거래처코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "거래처코드": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "거래처.시도": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "거래처",
                    "ConceptualProperty": "시도"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "시도": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "거래처.채널": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "거래처",
                    "ConceptualProperty": "채널"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "채널": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "날짜": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "ID"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "날짜.날짜": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "날짜"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "날짜": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  }
                ]
              },
              "날짜.날짜.변형.날짜_계층": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "Hierarchy": "날짜 계층",
                    "VariationSet": "변형",
                    "VariationSource": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "날짜 계층": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.날짜.변형.날짜_계층.분기": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "분기",
                    "VariationSet": "변형",
                    "VariationSource": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "분기": {
                      "State": "Generated"
                    }
                  },
                  {
                    "날짜 분기": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.날짜.변형.날짜_계층.연도": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "연도",
                    "VariationSet": "변형",
                    "VariationSource": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "연도": {
                      "State": "Generated"
                    }
                  },
                  {
                    "날짜 연도": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.날짜.변형.날짜_계층.월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "월",
                    "VariationSet": "변형",
                    "VariationSource": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "월": {
                      "State": "Generated"
                    }
                  },
                  {
                    "날짜 월": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.날짜.변형.날짜_계층.일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "Hierarchy": "날짜 계층",
                    "HierarchyLevel": "일",
                    "VariationSet": "변형",
                    "VariationSource": "날짜"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "일": {
                      "State": "Generated"
                    }
                  },
                  {
                    "날짜 일": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.연도": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "연도"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "연도": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.연월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "연월"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "연월": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.영문월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "영문월"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "영문월": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.요일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "요일"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "요일": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.월": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "월"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "월": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "날짜.일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "날짜",
                    "ConceptualProperty": "일"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "일": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "분석항목": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "분석항목"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "분석항목": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "분석항목.매개_변수": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "분석항목",
                    "ConceptualProperty": "매개 변수"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매개 변수": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "분석항목.매개_변수_주문": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "분석항목",
                    "ConceptualProperty": "매개 변수 주문"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매개 변수 주문": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "분석항목.매개_변수_필드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "분석항목",
                    "ConceptualProperty": "매개 변수 필드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매개 변수 필드": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "자전거_대여이력": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "자전거 대여이력": {
                      "State": "Generated"
                    }
                  },
                  {
                    "자전거_대여이력": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "자전거_대여이력.대여_대여소명": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "대여_대여소명"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "대여 대여소명": {
                      "State": "Generated"
                    }
                  },
                  {
                    "대여_대여소명": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "자전거_대여이력.대여_대여소번호": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "대여_대여소번호"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "대여 대여소번호": {
                      "State": "Generated"
                    }
                  },
                  {
                    "대여_대여소번호": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "자전거_대여이력.대여건수": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "대여건수"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "대여건수": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "자전거_대여이력.대여일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "대여일"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "대여일": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  }
                ]
              },
              "자전거_대여이력.이용거리": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "이용거리"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "이용거리": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "자전거_대여이력.이용시간": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "이용시간"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "이용시간": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "자전거_대여이력.일평균_대여건수": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "일평균 대여건수"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "일평균 대여건수": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "자전거_대여이력.자치구": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "자치구"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "자치구": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "자전거_대여이력.총대여건수": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "자전거_대여이력",
                    "ConceptualProperty": "총대여건수"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "총대여건수": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "ID"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "제품.단가": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "단가"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "단가": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.분류명": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "분류명"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "분류명": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.분류코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "분류코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "분류코드": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.사이즈": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "사이즈"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "사이즈": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.색상": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "색상"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "색상": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.수입자": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "수입자"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "수입자": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.원가": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "원가"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "원가": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.제조국": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "제조국"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제조국": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.제품명": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "제품명"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품명": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.제품분류명": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "제품분류명"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품분류명": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.제품분류코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "제품분류코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품분류코드": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "제품.제품코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "제품",
                    "ConceptualProperty": "제품코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품코드": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "판매": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.거래처코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "거래처코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "거래처코드": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "판매.단가": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "단가"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "단가": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.매출금액": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "매출금액"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매출금액": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.매출이익": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "매출이익"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매출이익": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.매출이익률": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "매출이익률"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "매출이익률": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.수량": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "수량"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "수량": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.전년대비_증감률": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "전년대비 증감률"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "전년대비 증감률": {
                      "State": "Generated"
                    }
                  },
                  {
                    "전년비": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "판매.전년대비_차이": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "전년대비 차이"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "전년대비 차이": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.전년동월_매출": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "전년동월 매출"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "전년동월 매출": {
                      "State": "Generated"
                    }
                  },
                  {
                    "전년동월": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "판매.제품코드": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "제품코드"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "제품코드": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "판매.총매출금액": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "총매출금액"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "총매출금액": {
                      "State": "Generated"
                    }
                  },
                  {
                    "당월": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "판매.총매출이익": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "총매출이익"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "총매출이익": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.총수량": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "총수량"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "총수량": {
                      "State": "Generated"
                    }
                  },
                  {
                    "수량": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "판매.판매ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "판매ID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "판매ID": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.판매건수": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "판매건수"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "판매건수": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "판매.판매일": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "판매",
                    "ConceptualProperty": "판매일"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "판매일": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "dim_date_date_has_변형_날짜_계층": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층"
                      },
                      "Subject": {
                        "Role": "dim_date.date"
                      }
                    },
                    "ID": "dates_have_날짜_계층",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date": {
                    "Target": {
                      "Entity": "dim_date.date"
                    }
                  },
                  "dim_date.date.변형.날짜_계층": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_has_분기": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_분기",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.분기"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_has_연도": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.연도"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_연도",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.연도": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_has_월": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_월",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_has_일": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.일"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_일",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.일": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.일"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_분기_has_dim_date_date_변형_날짜_계층_월": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      }
                    },
                    "ID": "분기_have_월1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      }
                    },
                    "ID": "월_have_분기1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "월_are_in_분기1",
                    "Preposition": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.분기"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_연도_has_dim_date_date_변형_날짜_계층_분기": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.연도"
                      }
                    },
                    "ID": "연도_have_분기",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.연도"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      }
                    },
                    "ID": "분기_have_연도",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "분기_are_in_연도1",
                    "Preposition": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.연도"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.분기"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.분기"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.연도": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_date_변형_날짜_계층_월_has_dim_date_date_변형_날짜_계층_일": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.일"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      }
                    },
                    "ID": "월_have_일1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.일"
                      }
                    },
                    "ID": "일_have_월1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "일_are_in_월1",
                    "Preposition": {
                      "Object": {
                        "Role": "dim_date.date.변형.날짜_계층.월"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "dim_date.date.변형.날짜_계층.일"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date.date.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.월"
                    }
                  },
                  "dim_date.date.변형.날짜_계층.일": {
                    "Target": {
                      "Entity": "dim_date.date.변형.날짜_계층.일"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_date": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.date": {
                    "Target": {
                      "Entity": "dim_date.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_연도": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.연도"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_연도",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.연도": {
                    "Target": {
                      "Entity": "dim_date.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_월": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.월"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_월",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.월": {
                    "Target": {
                      "Entity": "dim_date.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_자전거_대여이력_일평균_대여건수": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.일평균_대여건수"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_일평균_대여건수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "자전거_대여이력.일평균_대여건수": {
                    "Target": {
                      "Entity": "자전거_대여이력.일평균_대여건수"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_측정값_측정값_has_열1": {
                "Binding": {
                  "ConceptualEntity": "_측정값"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_측정값_측정값.열1"
                      },
                      "Subject": {
                        "Role": "v_측정값_측정값"
                      }
                    },
                    "ID": "Phrasing_측정값_have_열1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_측정값_측정값": {
                    "Target": {
                      "Entity": "v_측정값_측정값"
                    }
                  },
                  "v_측정값_측정값.열1": {
                    "Target": {
                      "Entity": "v_측정값_측정값.열1"
                    }
                  }
                },
                "State": "Generated"
              },
              "거래처_has_거래처명": {
                "Binding": {
                  "ConceptualEntity": "거래처"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "거래처.거래처명"
                      },
                      "Subject": {
                        "Role": "거래처"
                      }
                    },
                    "ID": "거래처_have_거래처명",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "거래처": {
                    "Target": {
                      "Entity": "거래처"
                    }
                  },
                  "거래처.거래처명": {
                    "Target": {
                      "Entity": "거래처.거래처명"
                    }
                  }
                },
                "State": "Generated"
              },
              "거래처_has_거래처코드": {
                "Binding": {
                  "ConceptualEntity": "거래처"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "거래처.거래처코드"
                      },
                      "Subject": {
                        "Role": "거래처"
                      }
                    },
                    "ID": "거래처_have_거래처코드",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "거래처": {
                    "Target": {
                      "Entity": "거래처"
                    }
                  },
                  "거래처.거래처코드": {
                    "Target": {
                      "Entity": "거래처.거래처코드"
                    }
                  }
                },
                "State": "Generated"
              },
              "거래처_has_시도": {
                "Binding": {
                  "ConceptualEntity": "거래처"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "거래처.시도"
                      },
                      "Subject": {
                        "Role": "거래처"
                      }
                    },
                    "ID": "거래처_have_시도",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "거래처": {
                    "Target": {
                      "Entity": "거래처"
                    }
                  },
                  "거래처.시도": {
                    "Target": {
                      "Entity": "거래처.시도"
                    }
                  }
                },
                "State": "Generated"
              },
              "거래처_has_채널": {
                "Binding": {
                  "ConceptualEntity": "거래처"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "거래처.채널"
                      },
                      "Subject": {
                        "Role": "거래처"
                      }
                    },
                    "ID": "거래처_have_채널",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "거래처": {
                    "Target": {
                      "Entity": "거래처"
                    }
                  },
                  "거래처.채널": {
                    "Target": {
                      "Entity": "거래처.채널"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_ID": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.ID"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_ID",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "ID_are_names_IDs_of_날짜",
                    "Name": {
                      "Name": {
                        "Role": "날짜.ID"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.ID": {
                    "Target": {
                      "Entity": "날짜.ID"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_날짜": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_날짜",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.날짜": {
                    "Target": {
                      "Entity": "날짜.날짜"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_연도": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.연도"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_연도",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.연도": {
                    "Target": {
                      "Entity": "날짜.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_연월": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.연월"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_연월",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.연월": {
                    "Target": {
                      "Entity": "날짜.연월"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_영문월": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.영문월"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_영문월",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.영문월": {
                    "Target": {
                      "Entity": "날짜.영문월"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_요일": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.요일"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_요일",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.요일": {
                    "Target": {
                      "Entity": "날짜.요일"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_월": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.월"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_월",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.월": {
                    "Target": {
                      "Entity": "날짜.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_has_일": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.일"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_일",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "날짜.일": {
                    "Target": {
                      "Entity": "날짜.일"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_has_변형_날짜_계층": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층"
                      },
                      "Subject": {
                        "Role": "날짜.날짜"
                      }
                    },
                    "ID": "날짜_have_날짜_계층",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜": {
                    "Target": {
                      "Entity": "날짜.날짜"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_has_분기": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_분기1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.분기"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_has_연도": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.연도"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_연도1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.연도": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_has_월": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_월1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_has_일": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.일"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층"
                      }
                    },
                    "ID": "날짜_계층_have_일1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.일": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.일"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_분기_has_날짜_날짜_변형_날짜_계층_월": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      }
                    },
                    "ID": "분기_have_월",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      }
                    },
                    "ID": "월_have_분기",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "월_are_in_분기",
                    "Preposition": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.분기"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.월"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_연도_has_날짜_날짜_변형_날짜_계층_분기": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.연도"
                      }
                    },
                    "ID": "연도_have_분기1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.연도"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      }
                    },
                    "ID": "분기_have_연도1",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "분기_are_in_연도",
                    "Preposition": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.연도"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.분기"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층.분기": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.분기"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.연도": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.연도"
                    }
                  }
                },
                "State": "Generated"
              },
              "날짜_날짜_변형_날짜_계층_월_has_날짜_날짜_변형_날짜_계층_일": {
                "Binding": {
                  "ConceptualEntity": "날짜"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.일"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      }
                    },
                    "ID": "월_have_일",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      },
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.일"
                      }
                    },
                    "ID": "일_have_월",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "일_are_in_월",
                    "Preposition": {
                      "Object": {
                        "Role": "날짜.날짜.변형.날짜_계층.월"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "날짜.날짜.변형.날짜_계층.일"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜.날짜.변형.날짜_계층.월": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.월"
                    }
                  },
                  "날짜.날짜.변형.날짜_계층.일": {
                    "Target": {
                      "Entity": "날짜.날짜.변형.날짜_계층.일"
                    }
                  }
                },
                "State": "Generated"
              },
              "분석항목_has_매개_변수": {
                "Binding": {
                  "ConceptualEntity": "분석항목"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "분석항목.매개_변수"
                      },
                      "Subject": {
                        "Role": "분석항목"
                      }
                    },
                    "ID": "분석항목_have_매개_변수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "분석항목": {
                    "Target": {
                      "Entity": "분석항목"
                    }
                  },
                  "분석항목.매개_변수": {
                    "Target": {
                      "Entity": "분석항목.매개_변수"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_dim_date": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_dim_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_자전거_대여이력",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_대여_대여소명": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.대여_대여소명"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_대여_대여소명",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.대여_대여소명": {
                    "Target": {
                      "Entity": "자전거_대여이력.대여_대여소명"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_대여_대여소번호": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.대여_대여소번호"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_대여_대여소번호",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.대여_대여소번호": {
                    "Target": {
                      "Entity": "자전거_대여이력.대여_대여소번호"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_대여건수": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.대여건수"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_대여건수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.대여건수": {
                    "Target": {
                      "Entity": "자전거_대여이력.대여건수"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_대여일": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.대여일"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_대여일",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.대여일": {
                    "Target": {
                      "Entity": "자전거_대여이력.대여일"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_이용거리": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.이용거리"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_이용거리",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.이용거리": {
                    "Target": {
                      "Entity": "자전거_대여이력.이용거리"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_이용시간": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.이용시간"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_이용시간",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.이용시간": {
                    "Target": {
                      "Entity": "자전거_대여이력.이용시간"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_일평균_대여건수": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.일평균_대여건수"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_일평균_대여건수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.일평균_대여건수": {
                    "Target": {
                      "Entity": "자전거_대여이력.일평균_대여건수"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_자치구": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.자치구"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_자치구",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.자치구": {
                    "Target": {
                      "Entity": "자전거_대여이력.자치구"
                    }
                  }
                },
                "State": "Generated"
              },
              "자전거_대여이력_has_총대여건수": {
                "Binding": {
                  "ConceptualEntity": "자전거_대여이력"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "자전거_대여이력.총대여건수"
                      },
                      "Subject": {
                        "Role": "자전거_대여이력"
                      }
                    },
                    "ID": "자전거_대여이력_have_총대여건수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "자전거_대여이력": {
                    "Target": {
                      "Entity": "자전거_대여이력"
                    }
                  },
                  "자전거_대여이력.총대여건수": {
                    "Target": {
                      "Entity": "자전거_대여이력.총대여건수"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_ID": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.ID"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_ID",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "ID_are_names_IDs_of_제품",
                    "Name": {
                      "Name": {
                        "Role": "제품.ID"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.ID": {
                    "Target": {
                      "Entity": "제품.ID"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_단가": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.단가"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_단가",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.단가": {
                    "Target": {
                      "Entity": "제품.단가"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_분류명": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.분류명"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_분류명",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.분류명": {
                    "Target": {
                      "Entity": "제품.분류명"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_분류코드": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.분류코드"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_분류코드",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.분류코드": {
                    "Target": {
                      "Entity": "제품.분류코드"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_사이즈": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.사이즈"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_사이즈",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.사이즈": {
                    "Target": {
                      "Entity": "제품.사이즈"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_색상": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.색상"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_색상",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.색상": {
                    "Target": {
                      "Entity": "제품.색상"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_수입자": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.수입자"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_수입자",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.수입자": {
                    "Target": {
                      "Entity": "제품.수입자"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_원가": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.원가"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_원가",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.원가": {
                    "Target": {
                      "Entity": "제품.원가"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_제조국": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.제조국"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_제조국",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.제조국": {
                    "Target": {
                      "Entity": "제품.제조국"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_제품명": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.제품명"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_제품명",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.제품명": {
                    "Target": {
                      "Entity": "제품.제품명"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_제품분류명": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.제품분류명"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_제품분류명",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.제품분류명": {
                    "Target": {
                      "Entity": "제품.제품분류명"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_제품분류코드": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.제품분류코드"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_제품분류코드",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.제품분류코드": {
                    "Target": {
                      "Entity": "제품.제품분류코드"
                    }
                  }
                },
                "State": "Generated"
              },
              "제품_has_제품코드": {
                "Binding": {
                  "ConceptualEntity": "제품"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품.제품코드"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_제품코드",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "제품.제품코드": {
                    "Target": {
                      "Entity": "제품.제품코드"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_거래처": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "거래처"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_거래처",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매"
                      },
                      "Subject": {
                        "Role": "거래처"
                      }
                    },
                    "ID": "거래처_have_판매",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "거래처": {
                    "Target": {
                      "Entity": "거래처"
                    }
                  },
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_날짜": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "날짜"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_날짜",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매"
                      },
                      "Subject": {
                        "Role": "날짜"
                      }
                    },
                    "ID": "날짜_have_판매",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "날짜": {
                    "Target": {
                      "Entity": "날짜"
                    }
                  },
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_단가": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.단가"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_단가",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.단가": {
                    "Target": {
                      "Entity": "판매.단가"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_매출금액": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.매출금액"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_매출금액",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.매출금액": {
                    "Target": {
                      "Entity": "판매.매출금액"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_매출이익": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.매출이익"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_매출이익",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.매출이익": {
                    "Target": {
                      "Entity": "판매.매출이익"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_매출이익률": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.매출이익률"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_매출이익률",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.매출이익률": {
                    "Target": {
                      "Entity": "판매.매출이익률"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_수량": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.수량"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_수량",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.수량": {
                    "Target": {
                      "Entity": "판매.수량"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_전년대비_증감률": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.전년대비_증감률"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_전년대비_증감률",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.전년대비_증감률": {
                    "Target": {
                      "Entity": "판매.전년대비_증감률"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_전년대비_차이": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.전년대비_차이"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_전년대비_차이",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.전년대비_차이": {
                    "Target": {
                      "Entity": "판매.전년대비_차이"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_전년동월_매출": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.전년동월_매출"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_전년동월_매출",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.전년동월_매출": {
                    "Target": {
                      "Entity": "판매.전년동월_매출"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_제품": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "제품"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_제품",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매"
                      },
                      "Subject": {
                        "Role": "제품"
                      }
                    },
                    "ID": "제품_have_판매",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "제품": {
                    "Target": {
                      "Entity": "제품"
                    }
                  },
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_총매출금액": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.총매출금액"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_총매출금액",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.총매출금액": {
                    "Target": {
                      "Entity": "판매.총매출금액"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_총매출이익": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.총매출이익"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_총매출이익",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.총매출이익": {
                    "Target": {
                      "Entity": "판매.총매출이익"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_총수량": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.총수량"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_총수량",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.총수량": {
                    "Target": {
                      "Entity": "판매.총수량"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_판매ID": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.판매ID"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_판매IDs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.판매ID": {
                    "Target": {
                      "Entity": "판매.판매ID"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_판매건수": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.판매건수"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_판매건수",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.판매건수": {
                    "Target": {
                      "Entity": "판매.판매건수"
                    }
                  }
                },
                "State": "Generated"
              },
              "판매_has_판매일": {
                "Binding": {
                  "ConceptualEntity": "판매"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "판매.판매일"
                      },
                      "Subject": {
                        "Role": "판매"
                      }
                    },
                    "ID": "판매_have_판매일",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "판매": {
                    "Target": {
                      "Entity": "판매"
                    }
                  },
                  "판매.판매일": {
                    "Target": {
                      "Entity": "판매.판매일"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "대여소현황",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제1_데이터\\자전거_대여현황.xlsx\"), null, true),",
          "    대여소현황_Sheet = 원본{[Item=\"대여소현황\",Kind=\"Sheet\"]}[Data],",
          "    #\"승격된 헤더\" = Table.PromoteHeaders(대여소현황_Sheet, [PromoteAllScalars=true]),",
          "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"대여소번호\", Int64.Type}, {\"대여소명\", type text}, {\"자치구\", type text}, {\"상세주소\", type text}, {\"위도\", type number}, {\"경도\", type number}, {\"설치시기\", type any}, {\"거치대수(LCD)\", Int64.Type}, {\"거치대수(QR)\", Int64.Type}, {\"운영방식\", type text}})",
          "in",
          "    #\"변경된 유형\""
        ],
        "kind": "m",
        "lineageTag": "ebc4c8f0-9be3-4c77-bebd-39bb6c3a78d7"
      }
    ],
    "relationships": [
      {
        "name": "56612444-3b75-4d40-bb22-16d1d93e9c82",
        "fromColumn": "날짜",
        "fromTable": "날짜",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233"
      },
      {
        "name": "bcc7d14d-eed4-4e3f-96c4-fcc2a5205f98",
        "fromColumn": "거래처코드",
        "fromTable": "판매",
        "toColumn": "거래처코드",
        "toTable": "거래처"
      },
      {
        "name": "0f2c3fd8-2f28-497b-a3a9-0b01277d8c3a",
        "fromColumn": "제품코드",
        "fromTable": "판매",
        "toColumn": "제품코드",
        "toTable": "제품"
      },
      {
        "name": "8d0975cd-71fc-4e4a-9e69-0eb734ca9406",
        "fromColumn": "판매일",
        "fromTable": "판매",
        "toColumn": "날짜",
        "toTable": "날짜"
      },
      {
        "name": "7d960f5b-3a86-4e3f-8ff0-796baee21d44",
        "fromColumn": "Date",
        "fromTable": "DimDate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040"
      },
      {
        "name": "a73406c7-187a-93d8-a025-d5dc8ea570f6",
        "fromColumn": "대여일",
        "fromTable": "자전거_대여이력",
        "toColumn": "Date",
        "toTable": "DimDate"
      }
    ],
    "roles": [
      {
        "name": "test",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3c088b3153f94b1fbe39e603b8000503"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "거래처",
            "filterExpression": "[거래처코드] == 1"
          }
        ]
      },
      {
        "name": "제목 없음",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "179cb92f34234032ad1b6397c4e0cdcf"
          }
        ],
        "modelPermission": "read"
      }
    ],
    "sourceQueryCulture": "ko-KR",
    "tables": [
      {
        "name": "거래처",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "거래처코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9faa600d-8067-4ed7-b648-df2c120299be",
            "sourceColumn": "거래처코드",
            "summarizeBy": "none"
          },
          {
            "name": "거래처명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09eaa656-5718-4519-b549-52c52cc526fd",
            "sourceColumn": "거래처명",
            "summarizeBy": "none"
          },
          {
            "name": "채널",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d6d2d2f-6954-4f84-ac34-ad496e6763b8",
            "sourceColumn": "채널",
            "summarizeBy": "none"
          },
          {
            "name": "시도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56de8d3a-e007-4ef0-b3b3-5ecfc5d7d8ce",
            "sourceColumn": "시도",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "81a09dc3-416a-4226-85c2-ae7ba844d49a",
        "partitions": [
          {
            "name": "거래처",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제2,3_데이터\\판매실적.xlsx\"), null, true),",
                "    거래처_Table = 원본{[Item=\"거래처\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(거래처_Table, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"거래처코드\", Int64.Type}, {\"거래처명\", type text}, {\"채널\", type text}, {\"시도\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_42b10947-eb17-4212-8f3d-a1459bb1bf48",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e6c9a2b3-5564-4aea-aff3-543c431344fe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "edc5dab8-84ff-4ffa-8f74-2dd64f7f5670",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ee1f6a81-ac66-43fb-bdb8-213100e4c03a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "79c69622-9ab8-44ac-97e5-b43699eb9cdb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca36467f-4daa-4d72-9e4b-1434bf2fee74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b44c08fe-f994-4bea-8be0-a443e2e47232",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64739535-504d-40e0-81a5-f82f63956fff",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "611356c9-42f2-4d32-8113-9eccc9db0d45",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "3cbfa2a2-10ee-4805-9eb9-5804f94a77ea",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "ca228cae-6bf4-463e-a213-39034c230b16",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "b5a3e154-d9b9-49c8-bb58-e203d04623dc",
                "ordinal": 3
              }
            ],
            "lineageTag": "927d4327-3d14-4fce-adc6-991b8dc7a586"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5dd8ba91-cf07-4bbf-8718-6db8b705f4d9",
        "partitions": [
          {
            "name": "DateTableTemplate_42b10947-eb17-4212-8f3d-a1459bb1bf48",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "날짜",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da6e9448-e229-4510-8ea1-f3b4f468ff24",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "날짜",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8acb602b-b97a-4dd8-bcde-1c40d7139014",
            "sourceColumn": "날짜",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233"
                },
                "isDefault": true,
                "relationship": "56612444-3b75-4d40-bb22-16d1d93e9c82"
              }
            ]
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e25b3870-6ff1-40bd-923e-2ba4af8fa3e3",
            "sourceColumn": "연도",
            "summarizeBy": "sum"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c893d9c7-3302-4e3c-ba3e-7af830e13490",
            "sourceColumn": "월",
            "summarizeBy": "sum"
          },
          {
            "name": "연월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba52701d-2db4-49cf-bb47-edd4d2f362af",
            "sourceColumn": "연월",
            "summarizeBy": "none"
          },
          {
            "name": "영문월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75407667-2228-4b09-931e-588e2eebfb5b",
            "sourceColumn": "영문월",
            "summarizeBy": "none"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40c1317f-54b6-4b18-8d96-5e931417c5b9",
            "sourceColumn": "일",
            "summarizeBy": "sum"
          },
          {
            "name": "요일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72cfb1a5-a47b-45ee-a629-70065bf5f9ef",
            "sourceColumn": "요일",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "79f60fe9-0aaa-421a-b039-1d946c5addfa",
        "partitions": [
          {
            "name": "날짜",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제2,3_데이터\\판매실적.xlsx\"), null, true),",
                "    날짜_Table = 원본{[Item=\"날짜\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(날짜_Table, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"ID\", Int64.Type}, {\"날짜\", type date}, {\"연도\", Int64.Type}, {\"월\", Int64.Type}, {\"연월\", type text}, {\"영문월\", type text}, {\"일\", Int64.Type}, {\"요일\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b8438f64-fa1b-4710-9113-896fc175f1ce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e913a9d-d934-4ffe-8a46-8c82ecb884e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "af5e8c90-37a0-4842-a30d-5e265df08094",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abe5f482-c468-4bd6-ace4-13af92db9da2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec62302f-cc95-4f1e-9da7-20dee636c927",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "046bf4f8-64db-4860-b909-96e6f39f29cb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e0bbba22-6346-4181-ab13-0803ab7e8dd0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "55b15473-8e81-40c6-9575-a8cfcd801975",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "fabd6709-7ae2-445f-906d-09d628290f85",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "9c2358af-1267-4e9b-8ab3-d7aca27b6a15",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "b6911dd6-e185-4d2a-bce3-bd067b85f597",
                "ordinal": 3
              }
            ],
            "lineageTag": "d1c040c5-281e-44f5-9328-1aa409f00297"
          }
        ],
        "isHidden": true,
        "lineageTag": "50970c7e-3466-4608-89e6-d390d22ac51d",
        "partitions": [
          {
            "name": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('날짜'[날짜])), 1, 1), Date(Year(MAX('날짜'[날짜])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "판매",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "판매ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a389fe11-11ef-4856-81f6-0b84b7f1fc42",
            "sourceColumn": "판매ID",
            "summarizeBy": "count"
          },
          {
            "name": "판매일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "cbed3d5f-6c42-4f33-b2c0-d2a1b364a1d9",
            "sourceColumn": "판매일",
            "summarizeBy": "none"
          },
          {
            "name": "거래처코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06b89a97-5ac4-467e-82ea-e4b40c044717",
            "sourceColumn": "거래처코드",
            "summarizeBy": "none"
          },
          {
            "name": "제품코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bef446b-0dd0-49a4-911f-ddaea6b8a4f0",
            "sourceColumn": "제품코드",
            "summarizeBy": "none"
          },
          {
            "name": "단가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a930f8f1-11d2-4d19-b548-389f54af1b85",
            "sourceColumn": "단가",
            "summarizeBy": "sum"
          },
          {
            "name": "수량",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "409e8feb-536a-4481-b364-d5afc0273d88",
            "sourceColumn": "수량",
            "summarizeBy": "sum"
          },
          {
            "name": "매출금액",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "afb8c9bd-a26b-4442-b386-9b49bc4186d4",
            "sourceColumn": "매출금액",
            "summarizeBy": "sum"
          },
          {
            "name": "매출이익",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec44ddf4-feef-4720-9dfe-cca7414b290d",
            "sourceColumn": "매출이익",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a3759af9-a666-459e-b2b1-302f09a33ac1",
        "measures": [
          {
            "name": "총매출금액",
            "expression": "SUM('판매'[매출금액])",
            "formatString": "#,0",
            "lineageTag": "554a61a0-a207-43fc-9ed9-53baaac19c7d"
          },
          {
            "name": "총매출이익",
            "expression": "SUM('판매'[매출이익])",
            "formatString": "#,0",
            "lineageTag": "6cbdd2fa-724c-4b05-b444-763b47ad381f"
          },
          {
            "name": "총수량",
            "expression": "SUM('판매'[수량])",
            "formatString": "#,0",
            "lineageTag": "bc935ebc-4c82-4d78-82a6-d8b04178b633"
          },
          {
            "name": "판매건수",
            "expression": "COUNT('판매'[판매ID]) ",
            "formatString": "#,0",
            "lineageTag": "9bf02b16-745d-4936-8ae3-92d66482d563"
          },
          {
            "name": "전년동월 매출",
            "expression": "CALCULATE([총매출금액], SAMEPERIODLASTYEAR('날짜'[날짜]))",
            "formatString": "#,0",
            "lineageTag": "416fea3e-a556-44e9-9024-5c265f24e64c"
          },
          {
            "name": "전년대비 증감률",
            "expression": "DIVIDE([총매출금액]-[전년동월 매출], [전년동월 매출], 1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "adb8883d-895a-4834-87e1-bcd3e1d03421"
          },
          {
            "name": "전년대비 차이",
            "expression": "[총매출금액] - [전년동월 매출]",
            "formatString": "#,0",
            "lineageTag": "8dbe202c-2681-4c5b-9b8a-472d0895d82a"
          },
          {
            "name": "매출이익률",
            "expression": "DIVIDE([총매출금액]-[총매출이익], [총매출이익], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "941dfd4f-968e-4e23-ad8d-c35dbee400b6"
          }
        ],
        "partitions": [
          {
            "name": "판매",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제2,3_데이터\\판매실적.xlsx\"), null, true),",
                "    판매_Table = 원본{[Item=\"판매\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(판매_Table, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"판매ID\", Int64.Type}, {\"판매일\", type date}, {\"거래처코드\", Int64.Type}, {\"제품코드\", type text}, {\"단가\", Int64.Type}, {\"수량\", Int64.Type}, {\"매출금액\", Int64.Type}, {\"매출이익\", Int64.Type}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "제품",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee395c34-4571-4e3a-b39d-ddd07f224398",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "분류코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b82381c8-676a-462d-bc71-6a7ad37c3059",
            "sourceColumn": "분류코드",
            "summarizeBy": "none"
          },
          {
            "name": "분류명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86665500-c3f7-43b5-9b69-2cf8686cdc20",
            "sourceColumn": "분류명",
            "summarizeBy": "none"
          },
          {
            "name": "제품분류코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38a6cc67-92ab-48fa-8a53-0bed8c03cb25",
            "sourceColumn": "제품분류코드",
            "summarizeBy": "none"
          },
          {
            "name": "제품분류명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14809f3a-584a-451c-a75b-7895fc76e910",
            "sourceColumn": "제품분류명",
            "summarizeBy": "none"
          },
          {
            "name": "제품코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a98f28d2-0ab0-4098-9dfe-a3da916363ca",
            "sourceColumn": "제품코드",
            "summarizeBy": "none"
          },
          {
            "name": "제품명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49dfc0ff-cd17-4305-a65e-4b1b9f9c4762",
            "sourceColumn": "제품명",
            "summarizeBy": "none"
          },
          {
            "name": "색상",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0aa84c9e-1b4a-4b0c-a623-268b20b23f19",
            "sourceColumn": "색상",
            "summarizeBy": "none"
          },
          {
            "name": "사이즈",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a64c794-7480-4e3d-81e5-e9a68ee7fecf",
            "sourceColumn": "사이즈",
            "summarizeBy": "none"
          },
          {
            "name": "원가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30d20032-877e-4d1b-9b27-03390ef09d57",
            "sourceColumn": "원가",
            "summarizeBy": "none"
          },
          {
            "name": "단가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3da6395b-6939-4002-95bc-02afefc76fb9",
            "sourceColumn": "단가",
            "summarizeBy": "none"
          },
          {
            "name": "제조국",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4bebff2-6495-4233-9b87-730fa3d8b401",
            "sourceColumn": "제조국",
            "summarizeBy": "none"
          },
          {
            "name": "수입자",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e901b69f-49f6-42c0-ae6c-aecbf9319103",
            "sourceColumn": "수입자",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cb866fda-708b-4fac-ac09-3f007d4ae924",
        "partitions": [
          {
            "name": "제품",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제2,3_데이터\\판매실적.xlsx\"), null, true),",
                "    제품_Table = 원본{[Item=\"제품\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(제품_Table, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"ID\", Int64.Type}, {\"분류코드\", type text}, {\"분류명\", type text}, {\"제품분류코드\", type text}, {\"제품분류명\", type text}, {\"제품코드\", type text}, {\"제품명\", type text}, {\"색상\", type text}, {\"사이즈\", type text}, {\"원가\", Int64.Type}, {\"단가\", Int64.Type}, {\"제조국\", type text}, {\"수입자\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_측정값",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "열1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d1b56e-42f1-43dc-aa21-acf2758399a2",
            "sourceColumn": "열1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a1f06f0f-95fd-4abf-a740-10d00531dd5a",
        "measures": [
          {
            "name": "매출_매장",
            "expression": "CALCULATE([총매출금액], FILTER('거래처', [채널] = \"매장\"))",
            "formatString": "#,0",
            "lineageTag": "42c4dd0b-8049-4b96-93a1-4e8175a0636c"
          },
          {
            "name": "전월_매출",
            "expression": "CALCULATE([총매출금액], DATEADD('날짜'[날짜], -1, MONTH))",
            "formatString": "#,0",
            "lineageTag": "b7bef7f2-8ebb-4a8a-bbed-0835f8c213fd"
          },
          {
            "name": "연간_누계",
            "expression": "TOTALYTD([총매출금액], '날짜'[날짜])",
            "formatString": "#,0",
            "lineageTag": "021a2999-7ae0-40e1-8091-87666004e21c"
          },
          {
            "name": "순위",
            "expression": "RANKX(ALL('제품'[제품명]), [총수량], ,DESC,Dense)",
            "formatString": "0",
            "lineageTag": "2b665912-189a-4d58-a376-fc5283236c7f"
          }
        ],
        "partitions": [
          {
            "name": "_측정값",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [열1 = _t]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(원본,{{\"열1\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "자전거_대여이력",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "대여일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e3393085-a6d8-4000-87b9-67fff325e74d",
            "sourceColumn": "대여일",
            "summarizeBy": "none"
          },
          {
            "name": "대여_대여소번호",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5bb41cf-dd5b-48fa-b0f4-108854ab45bf",
            "sourceColumn": "대여_대여소번호",
            "summarizeBy": "sum"
          },
          {
            "name": "대여_대여소명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34244a5e-f3ef-4ed4-99dd-0ae53f840b6f",
            "sourceColumn": "대여_대여소명",
            "summarizeBy": "none"
          },
          {
            "name": "대여건수",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "6787c94e-32f1-4897-9825-e4e707012118",
            "sourceColumn": "대여건수",
            "summarizeBy": "sum"
          },
          {
            "name": "이용거리",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e29ea2c5-9137-40e7-92a4-381f219ef255",
            "sourceColumn": "이용거리",
            "summarizeBy": "sum"
          },
          {
            "name": "이용시간",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9abec6d-b9d5-45ef-ac5b-f7021ddd555c",
            "sourceColumn": "이용시간",
            "summarizeBy": "sum"
          },
          {
            "name": "자치구",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53bd7331-47e1-4711-8ff7-3ea2f941754c",
            "sourceColumn": "자치구",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5f2d7695-c6c7-48d8-914f-68f83b2e7349",
        "measures": [
          {
            "name": "일평균 대여건수",
            "expression": "DIVIDE([총대여건수], COUNTROWS('DimDate'),0)",
            "formatString": "#,0",
            "lineageTag": "d5c5f7d2-3d88-4b16-aef7-f7fb7f3295c5"
          },
          {
            "name": "총대여건수",
            "expression": [
              "SUM('자전거_대여이력'[대여건수])",
              "",
              "//var summ = SUM('자전거_대여이력'[대여건수])",
              "//RETURN FORMAT(summ, \"#,###\")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "c39c7eb9-e216-404d-afe4-807450c47d2d"
          }
        ],
        "partitions": [
          {
            "name": "자전거_대여이력",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\OneDrive - Zalesia Inc\\문서\\카카오톡 받은 파일\\경영정보시각화능력 실기 모의문제_파워BI-240808\\실기 모의문제_파워BI(A형)_240808\\소스\\문제1_데이터\\자전거_대여현황.xlsx\"), null, true),",
                "    자전거_대여이력_Sheet = 원본{[Item=\"자전거_대여이력\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(자전거_대여이력_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"대여일\", type date}, {\"대여_대여소번호\", Int64.Type}, {\"대여_대여소명\", type text}, {\"대여건수\", type any}, {\"이용거리\", type any}, {\"이용시간\", type any}}),",
                "    #\"필터링된 행\" = Table.SelectRows(#\"변경된 유형\", each ([대여_대여소번호] <> 210)),",
                "    #\"변경된 유형1\" = Table.TransformColumnTypes(#\"필터링된 행\",{{\"대여건수\", Int64.Type}, {\"이용시간\", Int64.Type}, {\"이용거리\", type number}}),",
                "    #\"병합된 쿼리\" = Table.NestedJoin(#\"변경된 유형1\", {\"대여_대여소번호\"}, 대여소현황, {\"대여소번호\"}, \"대여소현황\", JoinKind.LeftOuter),",
                "    #\"확장된 대여소현황\" = Table.ExpandTableColumn(#\"병합된 쿼리\", \"대여소현황\", {\"자치구\"}, {\"자치구\"})",
                "in",
                "    #\"확장된 대여소현황\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2509fafc5a854fdd9d0118ee3a565dae"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e555aeee-10d8-4e2b-bbe7-dae3299a9130",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040"
                },
                "isDefault": true,
                "relationship": "7d960f5b-3a86-4e3f-8ff0-796baee21d44"
              }
            ]
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3f3d7fae-e67d-472f-af30-9161c2f7b185",
            "sourceColumn": "[연도]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c072770f-0d6a-48a8-95c4-36d01680a431",
            "sourceColumn": "[월]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9509cf30-2581-4eb6-8806-8d05729b0b42",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": "ADDCOLUMNS(CALENDAR(DATE(2022,1,1), DATE(2022,3,31)), \"연도\", YEAR([Date]), \"월\", MONTH([Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3b62150d-1581-40b7-a0e4-72fda5f08901",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "818062e4-a916-4155-a875-bcc6efddec14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9ec112fa-3a30-4bd2-b936-27002553931f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3451ec3d-138e-4476-9f97-52207d354937",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2cddaaab-4995-43d4-8952-e529bb44aa6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4809928a-d2fe-4d3a-9365-a82f4cee7add",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3d856d6d-548b-4a95-88bf-ad53ed1731b0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "364a4342-be42-44dc-a7d5-2a68e8ccdd60",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "4295fb06-3a9e-4502-bc71-1c0dcb7fcaa0",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "61c2ccd2-35c7-489c-bc8d-3b70482cbadd",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "d2424e36-90c3-4fcf-a02b-13a917043450",
                "ordinal": 3
              }
            ],
            "lineageTag": "b90c6cd0-25ca-41de-834f-f4ac01551626"
          }
        ],
        "isHidden": true,
        "lineageTag": "9339e55e-89d4-4042-962b-7304fd0d5f79",
        "partitions": [
          {
            "name": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimDate'[Date])), 1, 1), Date(Year(MAX('DimDate'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "분석항목",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "78ff0fd099f54c2ab714417f143f467a"
          }
        ],
        "columns": [
          {
            "name": "매개 변수",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "17af3178-824b-4c4d-8004-42fa541021e9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "매개 변수 필드"
                }
              ]
            },
            "sortByColumn": "매개 변수 주문",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "매개 변수 필드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9cd48ecf-dd25-492f-924c-b2485c62c73b",
            "sortByColumn": "매개 변수 주문",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "매개 변수 주문",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "902ed3b1-8dcd-426e-b0f6-fc7cb4132bc9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8c8a1651-a227-4c1b-8e10-ca3302497c79",
        "partitions": [
          {
            "name": "분석항목",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"매출금액\", NAMEOF('판매'[총매출금액]), 0),",
                "    (\"수량\", NAMEOF('판매'[총수량]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}