{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimChannel\",\"DimProductCategory\",\"FactSales\",\"DimDate\",\"DimDate (2)\",\"AS에 대한 DirectQuery - A형_답안\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      }
    ],
    "culture": "ko-KR",
    "cultures": [
      {
        "name": "ko-KR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "AS에 대한 DirectQuery - A형_답안",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "True"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://api.powerbi.com/v1.0/myorg/TestT\", \"A형_답안\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"Model\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "5dc054de-2046-4543-aee1-c5aa4a471608"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_be634f0d-8f9b-4bf1-ba76-32a5374480a5",
        "fromColumn": "channelKey",
        "fromTable": "FactSales",
        "toColumn": "ChannelKey",
        "toTable": "DimChannel"
      },
      {
        "name": "AutoDetected_da2cd8c3-5518-43d3-af3c-36c9d7d363d6",
        "fromColumn": "DateKey",
        "fromTable": "FactSales",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "797c58b7-2cba-4aa5-8256-f8e3bda71835",
        "fromColumn": "날짜",
        "fromTable": "날짜",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233"
      },
      {
        "name": "90fa7b59-96cb-49b3-a24d-11bf9d059041",
        "fromColumn": "거래처코드",
        "fromTable": "판매",
        "toColumn": "거래처코드",
        "toTable": "거래처"
      },
      {
        "name": "eba28c75-7d05-466c-a9ab-1f92d2d08e2e",
        "fromColumn": "제품코드",
        "fromTable": "판매",
        "toColumn": "제품코드",
        "toTable": "제품"
      },
      {
        "name": "ef980efc-3bbd-4b4e-97f3-a7100703c983",
        "fromColumn": "판매일",
        "fromTable": "판매",
        "toColumn": "날짜",
        "toTable": "날짜"
      },
      {
        "name": "7b8d47b1-2dd6-4870-9432-3fd8bcfb6420",
        "fromColumn": "대여일",
        "fromTable": "자전거_대여이력",
        "toColumn": "Date",
        "toTable": "DimDate 2"
      },
      {
        "name": "bec260a9-3b85-4d7d-b4b6-ba0e7f66418c",
        "fromColumn": "Date",
        "fromTable": "DimDate 2",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040"
      }
    ],
    "sourceQueryCulture": "ko-KR",
    "tables": [
      {
        "name": "DimChannel",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "ChannelKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8323b4b5-c3ed-4b3e-97c1-f5ec30a183eb",
            "sourceColumn": "ChannelKey",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85e04f70-8d5e-4988-9d53-0b25bb76121f",
            "sourceColumn": "ChannelLabel",
            "summarizeBy": "none"
          },
          {
            "name": "ENG_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cbacd5e-79db-4e9e-8eb9-45f8e5a43a9a",
            "sourceColumn": "ENG_DESC",
            "summarizeBy": "none"
          },
          {
            "name": "KOR_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c408c246-33d5-49cc-bab3-6999db9893a7",
            "sourceColumn": "KOR_DESC",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ff979596-6b22-4bd1-8af3-491dc30ec621",
        "measures": [
          {
            "name": "전년당년",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "var SelectYear = MAX('DimDate'[년])",
              "var LastYear = CALCULATE(MAX('DimDate'[년]), DATEADD('DimDate'[Date], -1, YEAR))",
              "var SelectHeader1 = MAX('DimDate (2)'[년])",
              "var SelectHeader2 = MAX('DimDate (2)'[Header2])",
              "",
              "var SelectYearSales = SUM('FactSales'[Total_Sales])",
              "var SelectYearLastSales = CALCULATE(SUM('FactSales'[Total_Sales]), ",
              "                            DATEADD(DimDate[Date], -1, MONTH))",
              "var LastYearSales = CALCULATE(SUM('FactSales'[Total_Sales]), ",
              "                            DATEADD('DimDate'[Date], -1, YEAR))",
              "var LastYearLastSales = CALCULATE(SUM('FactSales'[Total_Sales]), ",
              "                            DATEADD(DimDate[Date], -1, MONTH))",
              "",
              "var SelectYearP = FORMAT(DIVIDE(SelectYearSales, SelectYearLastSales), \"#,##%\")",
              "var LastYearP = FORMAT(DIVIDE(LastYearSales, LastYearLastSales), \"#,##%\")",
              "",
              "RETURN SWITCH(TRUE(),",
              "        AND(SelectHeader1 = LastYear, SelectHeader2 = \"매출액\"), LastYearSales",
              "        , AND(SelectHeader1 = LastYear, SelectHeader2 = \"%\"), LastYearP",
              "        , AND(SelectHeader1 = SelectYear, SelectHeader2 = \"매출액\"), SelectYearSales",
              "        , AND(SelectHeader1 = SelectYear, SelectHeader2 = \"%\"), SelectYearP",
              "        )  ",
              ""
            ],
            "lineageTag": "f10b76c6-9ecd-4c67-aee9-a140457c8ca9"
          },
          {
            "name": "측정값",
            "expression": "1",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d0216e25-0a3e-46a2-9099-744ef0172556"
          },
          {
            "name": "측정값 2",
            "expression": "USERNAME()",
            "lineageTag": "f10cdef2-853b-4ce8-98e8-399dd9612927"
          }
        ],
        "partitions": [
          {
            "name": "DimChannel",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\Downloads\\데이터.xlsx\"), null, true),",
                "    DimChannel_Sheet = 원본{[Item=\"DimChannel\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(DimChannel_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"ChannelKey\", Int64.Type}, {\"ChannelLabel\", Int64.Type}, {\"ENG_DESC\", type text}, {\"KOR_DESC\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2c16d99-59e5-4877-9670-200aa07f8aee",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductCategory_ENG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a21b7113-cfba-4f31-a2a3-a83c13141226",
            "sourceColumn": "ProductCategory_ENG",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategory_KOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "659a2536-ff34-40b1-8139-fe7934ebfa65",
            "sourceColumn": "ProductCategory_KOR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dc7c3d5a-1139-4346-b691-a5c8642faa9d",
        "partitions": [
          {
            "name": "DimProductCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\Downloads\\데이터.xlsx\"), null, true),",
                "    DimProductCategory_Sheet = 원본{[Item=\"DimProductCategory\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(DimProductCategory_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"ProductCategoryKey\", Int64.Type}, {\"ProductCategory_ENG\", type text}, {\"ProductCategory_KOR\", type text}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactSales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47dfd08a-78ad-4a9c-a7dc-ef81b2dfb6cb",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "channelKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e5d9baf-006a-4ef1-b077-2b96805c5b51",
            "sourceColumn": "channelKey",
            "summarizeBy": "none"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97c5d5d6-9721-4481-9623-87dc186cac9d",
            "sourceColumn": "StoreKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37939000-23c9-4a96-bfec-309b241bf01b",
            "sourceColumn": "ProductKey",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ad336fa-78d2-4d94-a2c6-4e2d2e37c363",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "count"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ff4549d-a65b-4761-8b98-8b196308a4d8",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "027b4617-0510-4451-aa22-738b1534efd5",
            "sourceColumn": "SalesQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "2d57c1a3-1c41-4760-b1e0-75abf840322c",
            "sourceColumn": "Total_Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f17eadf-7517-479e-b079-04b14f69839f",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "69fb28f0-23d8-4ad1-b12a-fadc49166aa4",
        "partitions": [
          {
            "name": "FactSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\sunne\\Downloads\\데이터.xlsx\"), null, true),",
                "    FactSales_Sheet = 원본{[Item=\"FactSales\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(FactSales_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"DateKey\", type text}, {\"channelKey\", Int64.Type}, {\"StoreKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"CurrencyKey\", Int64.Type}, {\"UnitPrice\", Int64.Type}, {\"SalesQuantity\", Int64.Type}, {\"Total_Sales\", Int64.Type}, {\"SalesAmount\", Int64.Type}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "e114bece-5ed8-4701-8d58-26a951f271d1",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "년",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "930281f3-b23f-4cf3-b573-2a57fe65101b",
            "sourceColumn": "년",
            "summarizeBy": "none"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "602c56b2-6a07-41b8-90d9-a2ad3b00158f",
            "sourceColumn": "월",
            "summarizeBy": "none"
          },
          {
            "name": "Base_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "451280f8-e318-4acc-9762-75b3b29c50b0",
            "sourceColumn": "Base_Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e2f6095-3c36-4619-b263-80c0988f74db",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "af8326ed-17ca-477f-9c10-4f9af545f385",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    MinDate = Date.FromText(List.Min(FactSales[DateKey])),",
                "    MaxDate = Date.FromText(List.Max(FactSales[DateKey])),",
                "    MinDate_LastYear = Date.StartOfYear(Date.AddYears(MinDate, -1)),",
                "",
                "    NumOfDays = Duration.Days(MaxDate - MinDate_LastYear) + 1,",
                "    AllDates = List.Dates(MinDate_LastYear, NumOfDays, #duration(1, 0, 0, 0)),",
                "    #\"테이블로 변환됨\" = Table.FromList(AllDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"이름을 바꾼 열 수\" = Table.RenameColumns(#\"테이블로 변환됨\",{{\"Column1\", \"Date\"}}),",
                "    #\"삽입된 연도\" = Table.AddColumn(#\"이름을 바꾼 열 수\", \"년\", each Date.Year([Date]), Int64.Type),",
                "    #\"삽입된 월\" = Table.AddColumn(#\"삽입된 연도\", \"월\", each Date.Month([Date]), Int64.Type),",
                "    #\"삽입된 처음 문자\" = Table.AddColumn(#\"삽입된 월\", \"처음 문자\", each Text.Start(Text.From([Date], \"ko-KR\"), 7), type text),",
                "    #\"이름을 바꾼 열 수1\" = Table.RenameColumns(#\"삽입된 처음 문자\",{{\"처음 문자\", \"Base_Date\"}}),",
                "    #\"추가된 사용자 지정 항목\" = Table.AddColumn(#\"이름을 바꾼 열 수1\", \"DateKey\", each Date.ToText([Date], \"YYYYMMDD\")),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"추가된 사용자 지정 항목\",{{\"Date\", type date}})",
                "in",
                "    #\"변경된 유형\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "년",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5049986-4273-4278-9e37-f2a942a6042f",
            "sourceColumn": "년",
            "summarizeBy": "sum"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11075892-8505-4614-aba7-038dedb8937f",
            "sourceColumn": "월",
            "summarizeBy": "sum"
          },
          {
            "name": "Base_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdd5ee91-c302-4ecd-834d-bde06c06fad4",
            "sourceColumn": "Base_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Header2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc2386c3-0f4c-4d56-8dae-a9c1c1b03b19",
            "sourceColumn": "Header2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2d113597-01de-4d45-9160-1bee7ab71e70",
        "partitions": [
          {
            "name": "DimDate (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    MinDate = Date.FromText(List.Min(FactSales[DateKey])),",
                "    MaxDate = Date.FromText(List.Max(FactSales[DateKey])),",
                "    MinDate_LastYear = Date.StartOfYear(Date.AddYears(MinDate, -1)),",
                "",
                "    NumOfDays = Duration.Days(MaxDate - MinDate_LastYear) + 1,",
                "    AllDates = List.Dates(MinDate_LastYear, NumOfDays, #duration(1, 0, 0, 0)),",
                "    #\"테이블로 변환됨\" = Table.FromList(AllDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"이름을 바꾼 열 수\" = Table.RenameColumns(#\"테이블로 변환됨\",{{\"Column1\", \"Date\"}}),",
                "    #\"삽입된 연도\" = Table.AddColumn(#\"이름을 바꾼 열 수\", \"년\", each Date.Year([Date]), Int64.Type),",
                "    #\"삽입된 월\" = Table.AddColumn(#\"삽입된 연도\", \"월\", each Date.Month([Date]), Int64.Type),",
                "    #\"삽입된 처음 문자\" = Table.AddColumn(#\"삽입된 월\", \"처음 문자\", each Text.Start(Text.From([Date], \"ko-KR\"), 7), type text),",
                "    #\"이름을 바꾼 열 수1\" = Table.RenameColumns(#\"삽입된 처음 문자\",{{\"처음 문자\", \"Base_Date\"}}),",
                "    #\"제거된 열 수\" = Table.RemoveColumns(#\"이름을 바꾼 열 수1\",{\"Date\"}),",
                "    #\"제거된 중복 항목 수\" = Table.Distinct(#\"제거된 열 수\", {\"Base_Date\"}),",
                "    #\"Add header level 2\" = Table.AddColumn(#\"제거된 중복 항목 수\", \"Header2\", each {\"매출액\", \"%\"}),",
                "    #\"Expanded Month\" = Table.ExpandListColumn(#\"Add header level 2\", \"Header2\")",
                "",
                "in",
                "    #\"Expanded Month\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "거래처",
        "columns": [
          {
            "name": "거래처코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e88b45a4-015e-408c-972a-3b01dce4dc48",
            "sourceColumn": "거래처코드",
            "sourceLineageTag": "9faa600d-8067-4ed7-b648-df2c120299be",
            "summarizeBy": "none"
          },
          {
            "name": "거래처명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "e70799cb-8f3c-4370-993b-dd6d724422eb",
            "sourceColumn": "거래처명",
            "sourceLineageTag": "09eaa656-5718-4519-b549-52c52cc526fd",
            "summarizeBy": "none"
          },
          {
            "name": "채널",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "db51aabd-19ff-44fd-91c4-3d63e6e46bbd",
            "sourceColumn": "채널",
            "sourceLineageTag": "1d6d2d2f-6954-4f84-ac34-ad496e6763b8",
            "summarizeBy": "none"
          },
          {
            "name": "시도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "98084548-b6d4-4a97-a732-a943408eff60",
            "sourceColumn": "시도",
            "sourceLineageTag": "56de8d3a-e007-4ef0-b3b3-5ecfc5d7d8ce",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "69f661cc-84b2-4a62-aae6-a0c89a9b5160",
        "partitions": [
          {
            "name": "거래처",
            "mode": "directQuery",
            "source": {
              "entityName": "거래처",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "81a09dc3-416a-4226-85c2-ae7ba844d49a"
      },
      {
        "name": "날짜",
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9b3cd069-4781-433d-81a2-02a1c27dad66",
            "sourceColumn": "ID",
            "sourceLineageTag": "da6e9448-e229-4510-8ea1-f3b4f468ff24",
            "summarizeBy": "count"
          },
          {
            "name": "날짜",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isNullable": false,
            "lineageTag": "66244100-65df-4bfb-b663-f58fd7f70b16",
            "sourceColumn": "날짜",
            "sourceLineageTag": "8acb602b-b97a-4dd8-bcde-1c40d7139014",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233"
                },
                "isDefault": true,
                "relationship": "797c58b7-2cba-4aa5-8256-f8e3bda71835"
              }
            ]
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a705866-a0fe-4294-a032-085efad5fe9d",
            "sourceColumn": "연도",
            "sourceLineageTag": "e25b3870-6ff1-40bd-923e-2ba4af8fa3e3",
            "summarizeBy": "sum"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e33f14bc-92cc-4bd0-aecb-081992f19c4c",
            "sourceColumn": "월",
            "sourceLineageTag": "c893d9c7-3302-4e3c-ba3e-7af830e13490",
            "summarizeBy": "sum"
          },
          {
            "name": "연월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "977b8a74-7029-4e61-8c6c-b9bcfff2ebf8",
            "sourceColumn": "연월",
            "sourceLineageTag": "ba52701d-2db4-49cf-bb47-edd4d2f362af",
            "summarizeBy": "none"
          },
          {
            "name": "영문월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "8dbeecb7-e7e7-470d-8d96-22073311e987",
            "sourceColumn": "영문월",
            "sourceLineageTag": "75407667-2228-4b09-931e-588e2eebfb5b",
            "summarizeBy": "none"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c33ce511-8851-4793-bea0-4e70a52883a3",
            "sourceColumn": "일",
            "sourceLineageTag": "40c1317f-54b6-4b18-8d96-5e931417c5b9",
            "summarizeBy": "sum"
          },
          {
            "name": "요일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "af4b8e23-65b4-493d-a231-8467e8ecae0a",
            "sourceColumn": "요일",
            "sourceLineageTag": "72cfb1a5-a47b-45ee-a629-70065bf5f9ef",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c939f1b8-10cb-4d87-8e1d-27603b10dbf5",
        "partitions": [
          {
            "name": "날짜",
            "mode": "directQuery",
            "source": {
              "entityName": "날짜",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "79f60fe9-0aaa-421a-b039-1d946c5addfa"
      },
      {
        "name": "판매",
        "columns": [
          {
            "name": "판매ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51fd81b5-f8bc-4ff1-bb36-6f0830832277",
            "sourceColumn": "판매ID",
            "sourceLineageTag": "a389fe11-11ef-4856-81f6-0b84b7f1fc42",
            "summarizeBy": "count"
          },
          {
            "name": "판매일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "84dd5c65-d5a9-4b92-90b7-7a15756e040e",
            "sourceColumn": "판매일",
            "sourceLineageTag": "cbed3d5f-6c42-4f33-b2c0-d2a1b364a1d9",
            "summarizeBy": "none"
          },
          {
            "name": "거래처코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fa200a3-8dfe-41c0-99ef-a7aaaf1eda4e",
            "sourceColumn": "거래처코드",
            "sourceLineageTag": "06b89a97-5ac4-467e-82ea-e4b40c044717",
            "summarizeBy": "none"
          },
          {
            "name": "제품코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "55f2d417-ab4a-4377-b9f5-9735de1f0211",
            "sourceColumn": "제품코드",
            "sourceLineageTag": "3bef446b-0dd0-49a4-911f-ddaea6b8a4f0",
            "summarizeBy": "none"
          },
          {
            "name": "단가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c65703c-8bf0-4fbf-aed2-97cd8c2ab980",
            "sourceColumn": "단가",
            "sourceLineageTag": "a930f8f1-11d2-4d19-b548-389f54af1b85",
            "summarizeBy": "sum"
          },
          {
            "name": "수량",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42b76340-0784-41e1-8b8a-932cce61fb2f",
            "sourceColumn": "수량",
            "sourceLineageTag": "409e8feb-536a-4481-b364-d5afc0273d88",
            "summarizeBy": "sum"
          },
          {
            "name": "매출금액",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9262f0d6-3573-4513-b93c-adabae7ecd02",
            "sourceColumn": "매출금액",
            "sourceLineageTag": "afb8c9bd-a26b-4442-b386-9b49bc4186d4",
            "summarizeBy": "sum"
          },
          {
            "name": "매출이익",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e03d3714-d847-4ebe-a77b-140d22bae96f",
            "sourceColumn": "매출이익",
            "sourceLineageTag": "ec44ddf4-feef-4720-9dfe-cca7414b290d",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1a16f2fe-3a23-4cd2-b92f-49a68b7d36d0",
        "measures": [
          {
            "name": "총매출금액",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"총매출금액\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "8fcbd06d-9b43-4d3a-ae59-d4ce338b58b4",
            "sourceLineageTag": "554a61a0-a207-43fc-9ed9-53baaac19c7d"
          },
          {
            "name": "총매출이익",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"총매출이익\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "17fc5c8c-ebff-42d9-9961-fa5b1a5bd5ed",
            "sourceLineageTag": "6cbdd2fa-724c-4b05-b444-763b47ad381f"
          },
          {
            "name": "총수량",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"총수량\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "adb37618-14a6-4c81-9279-30921771a600",
            "sourceLineageTag": "bc935ebc-4c82-4d78-82a6-d8b04178b633"
          },
          {
            "name": "판매건수",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"판매건수\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "71df6d7d-b4b0-4dd8-98be-fac3b9a92161",
            "sourceLineageTag": "9bf02b16-745d-4936-8ae3-92d66482d563"
          },
          {
            "name": "전년동월 매출",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"전년동월 매출\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "348ec99e-4376-4fd0-8c6b-4fa27ba92e64",
            "sourceLineageTag": "416fea3e-a556-44e9-9024-5c265f24e64c"
          },
          {
            "name": "전년대비 증감률",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"전년대비 증감률\", DOUBLE, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ed648752-d42e-4072-a0c9-e7c85638ccbe",
            "sourceLineageTag": "adb8883d-895a-4834-87e1-bcd3e1d03421"
          },
          {
            "name": "전년대비 차이",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"전년대비 차이\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "1217eb3b-226b-444c-9368-0e57301240aa",
            "sourceLineageTag": "8dbe202c-2681-4c5b-9b8a-472d0895d82a"
          },
          {
            "name": "매출이익률",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"매출이익률\", DOUBLE, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "50a01875-6810-424c-8227-52a8f3279538",
            "sourceLineageTag": "941dfd4f-968e-4e23-ad8d-c35dbee400b6"
          }
        ],
        "partitions": [
          {
            "name": "판매",
            "mode": "directQuery",
            "source": {
              "entityName": "판매",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "a3759af9-a666-459e-b2b1-302f09a33ac1"
      },
      {
        "name": "제품",
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94d2b493-fc60-4240-b6dc-b589688de296",
            "sourceColumn": "ID",
            "sourceLineageTag": "ee395c34-4571-4e3a-b39d-ddd07f224398",
            "summarizeBy": "none"
          },
          {
            "name": "분류코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "d7a7b585-5c7b-46f7-9048-2cab51752fa4",
            "sourceColumn": "분류코드",
            "sourceLineageTag": "b82381c8-676a-462d-bc71-6a7ad37c3059",
            "summarizeBy": "none"
          },
          {
            "name": "분류명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "ab045894-630b-485d-a421-e1de0140ff52",
            "sourceColumn": "분류명",
            "sourceLineageTag": "86665500-c3f7-43b5-9b69-2cf8686cdc20",
            "summarizeBy": "none"
          },
          {
            "name": "제품분류코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "512fabdb-900a-4c7f-9d08-73bbc1e8d599",
            "sourceColumn": "제품분류코드",
            "sourceLineageTag": "38a6cc67-92ab-48fa-8a53-0bed8c03cb25",
            "summarizeBy": "none"
          },
          {
            "name": "제품분류명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "12ba8b2a-bbda-46f0-9255-14d3eeddebad",
            "sourceColumn": "제품분류명",
            "sourceLineageTag": "14809f3a-584a-451c-a75b-7895fc76e910",
            "summarizeBy": "none"
          },
          {
            "name": "제품코드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "70852491-58b2-4dcd-af17-7c219f90ac2d",
            "sourceColumn": "제품코드",
            "sourceLineageTag": "a98f28d2-0ab0-4098-9dfe-a3da916363ca",
            "summarizeBy": "none"
          },
          {
            "name": "제품명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "49712502-fadb-4183-9a35-23f78e8a9c8e",
            "sourceColumn": "제품명",
            "sourceLineageTag": "49dfc0ff-cd17-4305-a65e-4b1b9f9c4762",
            "summarizeBy": "none"
          },
          {
            "name": "색상",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "3a492125-f842-42b1-aeb0-6267d24ad10c",
            "sourceColumn": "색상",
            "sourceLineageTag": "0aa84c9e-1b4a-4b0c-a623-268b20b23f19",
            "summarizeBy": "none"
          },
          {
            "name": "사이즈",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "c63bf445-bc07-40c6-a0b7-4fcf61fe2663",
            "sourceColumn": "사이즈",
            "sourceLineageTag": "2a64c794-7480-4e3d-81e5-e9a68ee7fecf",
            "summarizeBy": "none"
          },
          {
            "name": "원가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3122c857-5800-404e-81b2-ae7b0f724c77",
            "sourceColumn": "원가",
            "sourceLineageTag": "30d20032-877e-4d1b-9b27-03390ef09d57",
            "summarizeBy": "none"
          },
          {
            "name": "단가",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a1356e9-4bf4-4ffa-b7f4-57f3cfde0d82",
            "sourceColumn": "단가",
            "sourceLineageTag": "3da6395b-6939-4002-95bc-02afefc76fb9",
            "summarizeBy": "none"
          },
          {
            "name": "제조국",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "b473d6e0-4d93-4880-8209-0dec74efaefd",
            "sourceColumn": "제조국",
            "sourceLineageTag": "b4bebff2-6495-4233-9b87-730fa3d8b401",
            "summarizeBy": "none"
          },
          {
            "name": "수입자",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "be50907b-37f5-4216-80dc-984bbe50b96c",
            "sourceColumn": "수입자",
            "sourceLineageTag": "e901b69f-49f6-42c0-ae6c-aecbf9319103",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e40ca5df-2876-47b9-866f-c148edc0ca78",
        "partitions": [
          {
            "name": "제품",
            "mode": "directQuery",
            "source": {
              "entityName": "제품",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "cb866fda-708b-4fac-ac09-3f007d4ae924"
      },
      {
        "name": "_측정값",
        "columns": [
          {
            "name": "열1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "2321a049-d5b4-4405-b33e-7fba66381587",
            "sourceColumn": "열1",
            "sourceLineageTag": "44d1b56e-42f1-43dc-aa21-acf2758399a2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "014cbdf9-6a99-4cc9-a395-a260ad272685",
        "measures": [
          {
            "name": "매출_매장",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"매출_매장\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "41aa3e9c-aba5-439b-83d6-fae635c9575f",
            "sourceLineageTag": "42c4dd0b-8049-4b96-93a1-4e8175a0636c"
          },
          {
            "name": "전월_매출",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"전월_매출\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "8f8f9949-3fe4-411d-aa6e-52b60977806a",
            "sourceLineageTag": "b7bef7f2-8ebb-4a8a-bbed-0835f8c213fd"
          },
          {
            "name": "연간_누계",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"연간_누계\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "5d026f75-96f0-4857-a8b0-5b205de10bc0",
            "sourceLineageTag": "021a2999-7ae0-40e1-8091-87666004e21c"
          },
          {
            "name": "순위",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"순위\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "0",
            "lineageTag": "76104808-2378-4f74-9959-b02432d6f5ab",
            "sourceLineageTag": "2b665912-189a-4d58-a376-fc5283236c7f"
          }
        ],
        "partitions": [
          {
            "name": "_측정값",
            "mode": "directQuery",
            "source": {
              "entityName": "_측정값",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "a1f06f0f-95fd-4abf-a740-10d00531dd5a"
      },
      {
        "name": "자전거_대여이력",
        "columns": [
          {
            "name": "대여일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "0ca888f1-4697-4a5c-b3c6-ea5a6d765d67",
            "sourceColumn": "대여일",
            "sourceLineageTag": "e3393085-a6d8-4000-87b9-67fff325e74d",
            "summarizeBy": "none"
          },
          {
            "name": "대여_대여소번호",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3f8928f-614b-40e0-826b-0e8553243fc3",
            "sourceColumn": "대여_대여소번호",
            "sourceLineageTag": "f5bb41cf-dd5b-48fa-b0f4-108854ab45bf",
            "summarizeBy": "sum"
          },
          {
            "name": "대여_대여소명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "b7c4ddcc-713b-4854-8846-f0cb54868e66",
            "sourceColumn": "대여_대여소명",
            "sourceLineageTag": "34244a5e-f3ef-4ed4-99dd-0ae53f840b6f",
            "summarizeBy": "none"
          },
          {
            "name": "대여건수",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "1b5a2226-a545-4d23-b957-f9d24ac41504",
            "sourceColumn": "대여건수",
            "sourceLineageTag": "6787c94e-32f1-4897-9825-e4e707012118",
            "summarizeBy": "sum"
          },
          {
            "name": "이용거리",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "3f603e35-2cc8-4a11-af6d-e73b38bcd652",
            "sourceColumn": "이용거리",
            "sourceLineageTag": "e29ea2c5-9137-40e7-92a4-381f219ef255",
            "summarizeBy": "sum"
          },
          {
            "name": "이용시간",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c754f99-1cf8-48e8-8ad8-b8bc03aa5a7f",
            "sourceColumn": "이용시간",
            "sourceLineageTag": "f9abec6d-b9d5-45ef-ac5b-f7021ddd555c",
            "summarizeBy": "sum"
          },
          {
            "name": "자치구",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "4e736b11-cc3d-4c19-befa-4f2d152e3a62",
            "sourceColumn": "자치구",
            "sourceLineageTag": "53bd7331-47e1-4711-8ff7-3ea2f941754c",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "146ade33-3774-45d6-8b96-5d2b475fc31b",
        "measures": [
          {
            "name": "일평균 대여건수",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"일평균 대여건수\", DOUBLE, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "56be5c53-aecb-4ecc-8e06-64194ac42b03",
            "sourceLineageTag": "d5c5f7d2-3d88-4b16-aef7-f7fb7f3295c5"
          },
          {
            "name": "총대여건수",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"총대여건수\", INTEGER, \"AS에 대한 DirectQuery - A형_답안\")",
            "formatString": "#,0",
            "lineageTag": "10f3bb10-39a2-4ad7-9184-3533756fa588",
            "sourceLineageTag": "c39c7eb9-e216-404d-afe4-807450c47d2d"
          }
        ],
        "partitions": [
          {
            "name": "자전거_대여이력",
            "mode": "directQuery",
            "source": {
              "entityName": "자전거_대여이력",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "5f2d7695-c6c7-48d8-914f-68f83b2e7349"
      },
      {
        "name": "DimDate 2",
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isNullable": false,
            "lineageTag": "aa47c141-1a3f-4907-8fa4-bfc78cce68b1",
            "sourceColumn": "Date",
            "sourceLineageTag": "e555aeee-10d8-4e2b-bbe7-dae3299a9130",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040"
                },
                "isDefault": true,
                "relationship": "bec260a9-3b85-4d7d-b4b6-ba0e7f66418c"
              }
            ]
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a4d2491-fffe-445b-a063-36375d28b7e5",
            "sourceColumn": "연도",
            "sourceLineageTag": "3f3d7fae-e67d-472f-af30-9161c2f7b185",
            "summarizeBy": "sum"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85a79d16-6cd1-4d22-a6d6-604cf9b51fd9",
            "sourceColumn": "월",
            "sourceLineageTag": "c072770f-0d6a-48a8-95c4-36d01680a431",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "66e8701d-861d-42f5-b4f9-887d8732babd",
        "partitions": [
          {
            "name": "DimDate 2",
            "mode": "directQuery",
            "source": {
              "entityName": "DimDate",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "9509cf30-2581-4eb6-8806-8d05729b0b42"
      },
      {
        "name": "분석항목",
        "columns": [
          {
            "name": "매개 변수",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "c47d2e79-4f8a-45cf-b30c-2eb80bcce102",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "매개 변수 필드"
                }
              ]
            },
            "sortByColumn": "매개 변수 주문",
            "sourceColumn": "매개 변수",
            "sourceLineageTag": "17af3178-824b-4c4d-8004-42fa541021e9",
            "summarizeBy": "none"
          },
          {
            "name": "매개 변수 필드",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "31efb391-5ebb-4391-b234-a7f0bb5e449d",
            "sortByColumn": "매개 변수 주문",
            "sourceColumn": "매개 변수 필드",
            "sourceLineageTag": "9cd48ecf-dd25-492f-924c-b2485c62c73b",
            "summarizeBy": "none"
          },
          {
            "name": "매개 변수 주문",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bff4e3c0-529d-4a96-a279-3ad3f6ead791",
            "sourceColumn": "매개 변수 주문",
            "sourceLineageTag": "902ed3b1-8dcd-426e-b0f6-fc7cb4132bc9",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f1bbacaa-f4a8-41c8-ba8a-5489f96e4293",
        "partitions": [
          {
            "name": "분석항목",
            "mode": "directQuery",
            "source": {
              "entityName": "분석항목",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "8c8a1651-a227-4c1b-8e10-ca3302497c79"
      },
      {
        "name": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233",
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "bb80d180-7594-4ac9-9b33-f761f010de16",
            "sourceColumn": "Date",
            "sourceLineageTag": "b8438f64-fa1b-4710-9113-896fc175f1ce",
            "summarizeBy": "none"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ba32ccfc-f431-4fb9-86c9-c9222c5e164d",
            "sourceColumn": "연도",
            "sourceLineageTag": "3e913a9d-d934-4ffe-8a46-8c82ecb884e5",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7169af37-6bcf-4d29-89a2-98e34a05690f",
            "sourceColumn": "MonthNo",
            "sourceLineageTag": "af5e8c90-37a0-4842-a30d-5e265df08094",
            "summarizeBy": "none"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fcaa1e4c-c212-4b28-880c-2ac866d17d6f",
            "sortByColumn": "MonthNo",
            "sourceColumn": "월",
            "sourceLineageTag": "abe5f482-c468-4bd6-ace4-13af92db9da2",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "fac40ca8-0c3f-430a-92fe-3c9dcfe8bfb7",
            "sourceColumn": "QuarterNo",
            "sourceLineageTag": "ec62302f-cc95-4f1e-9da7-20dee636c927",
            "summarizeBy": "none"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5d66ad90-c7ba-4079-9ddb-cfee3ebb27bd",
            "sortByColumn": "QuarterNo",
            "sourceColumn": "분기",
            "sourceLineageTag": "046bf4f8-64db-4860-b909-96e6f39f29cb",
            "summarizeBy": "none"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b9b41fce-ccfb-463e-b78f-6760f163bc43",
            "sourceColumn": "일",
            "sourceLineageTag": "e0bbba22-6346-4181-ab13-0803ab7e8dd0",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "6108cfb6-c937-46fb-9fd5-e8737c3edbaf",
                "ordinal": 0,
                "sourceLineageTag": "55b15473-8e81-40c6-9575-a8cfcd801975"
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "04e2a480-5e4e-4045-afbe-0674dc32c871",
                "ordinal": 1,
                "sourceLineageTag": "fabd6709-7ae2-445f-906d-09d628290f85"
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "e2121362-89cb-4506-9258-4de07676f853",
                "ordinal": 2,
                "sourceLineageTag": "9c2358af-1267-4e9b-8ab3-d7aca27b6a15"
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "2c16ddc9-c96b-42cd-9c26-d6ac57b642ee",
                "ordinal": 3,
                "sourceLineageTag": "b6911dd6-e185-4d2a-bce3-bd067b85f597"
              }
            ],
            "lineageTag": "12e8a738-1526-44f0-8887-1cd1e6f5b5ee",
            "sourceLineageTag": "d1c040c5-281e-44f5-9328-1aa409f00297"
          }
        ],
        "lineageTag": "d3a6d5ca-2913-4543-9b35-aa3800c34b02",
        "partitions": [
          {
            "name": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233",
            "mode": "directQuery",
            "source": {
              "entityName": "LocalDateTable_c7525723-3deb-4a97-9555-ecfec845d233",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "showAsVariationsOnly": true,
        "sourceLineageTag": "50970c7e-3466-4608-89e6-d390d22ac51d"
      },
      {
        "name": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040",
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "4015da92-29f0-4ebb-be1c-7777dc6c27e0",
            "sourceColumn": "Date",
            "sourceLineageTag": "3b62150d-1581-40b7-a0e4-72fda5f08901",
            "summarizeBy": "none"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "4bfd9c53-e941-4a27-9f71-40da12d02b73",
            "sourceColumn": "연도",
            "sourceLineageTag": "818062e4-a916-4155-a875-bcc6efddec14",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "527047f4-ee0f-4d35-b972-1c8c554e996e",
            "sourceColumn": "MonthNo",
            "sourceLineageTag": "9ec112fa-3a30-4bd2-b936-27002553931f",
            "summarizeBy": "none"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0c0f5023-dc1d-4179-8bfc-2c135c578565",
            "sortByColumn": "MonthNo",
            "sourceColumn": "월",
            "sourceLineageTag": "3451ec3d-138e-4476-9f97-52207d354937",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ace71dff-ae6a-45e8-9393-9011765df283",
            "sourceColumn": "QuarterNo",
            "sourceLineageTag": "2cddaaab-4995-43d4-8952-e529bb44aa6d",
            "summarizeBy": "none"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9add0d90-0f56-4e85-9749-1dcebea37a55",
            "sortByColumn": "QuarterNo",
            "sourceColumn": "분기",
            "sourceLineageTag": "4809928a-d2fe-4d3a-9365-a82f4cee7add",
            "summarizeBy": "none"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "41caceee-5a91-4f00-8de9-582496bd268a",
            "sourceColumn": "일",
            "sourceLineageTag": "3d856d6d-548b-4a95-88bf-ad53ed1731b0",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "53c4d431-e205-43a3-a5db-ac9ed54d26c6",
                "ordinal": 0,
                "sourceLineageTag": "364a4342-be42-44dc-a7d5-2a68e8ccdd60"
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "effbb5ef-aa01-4714-8b1d-313986364a41",
                "ordinal": 1,
                "sourceLineageTag": "4295fb06-3a9e-4502-bc71-1c0dcb7fcaa0"
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "024b6859-9265-4201-a972-6bc071367920",
                "ordinal": 2,
                "sourceLineageTag": "61c2ccd2-35c7-489c-bc8d-3b70482cbadd"
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "0a03a9c2-776d-41f9-8b6a-06efd8a39a32",
                "ordinal": 3,
                "sourceLineageTag": "d2424e36-90c3-4fcf-a02b-13a917043450"
              }
            ],
            "lineageTag": "bbcf44e8-c075-4b8b-bb4d-9a46a124d6b0",
            "sourceLineageTag": "b90c6cd0-25ca-41de-834f-f4ac01551626"
          }
        ],
        "lineageTag": "d0f1953d-ad3f-4ed7-adb7-28864dd674f5",
        "partitions": [
          {
            "name": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040",
            "mode": "directQuery",
            "source": {
              "entityName": "LocalDateTable_2eadbb5b-9845-45a1-a874-abeed9ec1040",
              "expressionSource": "AS에 대한 DirectQuery - A형_답안",
              "type": "entity"
            }
          }
        ],
        "showAsVariationsOnly": true,
        "sourceLineageTag": "9339e55e-89d4-4042-962b-7304fd0d5f79"
      }
    ]
  }
}